name: Rebuild the GTISC s2e image

on: 
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
      runs-on: [self-hosted, super]
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: build and push
          env:
            DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
            DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
          run: ./scripts/gtisc/docker_build/build_image_and_push.sh
